from tkinter import *
#from PIL import Image,ImageTk
root = Tk()
root.geometry("400x500")
scvalue = StringVar()
scvalue.set("")
screen = Entry(root, textvar=scvalue, font="aerial 80 bold")
screen.pack(ipadx=10, pady=8, padx=10)
#root_img = ImageTk.PhotoImage(Image.open("cal_icon.png"))
#cal_lable = Lable(root,image = root_img)
root.title("Welcome to calculator")
root.configure(background="light blue")

width = root.winfo_screenwidth()
height = root.winfo_screenheight()
#function needed
def click(event):
    global scvalue
    text = event.widget.cget("text")
    print(text)
    if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            value = eval(screen.get())
        scvalue.set(value)
        screen.update()
    elif text == "c":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get() + text)
        screen.update()

#frames
f1 = Frame(root, bg="darkgray")
b1 = Button(f1, text="9", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="8", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="7", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="/", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
f1.pack()
f1 = Frame(root, bg="darkgray")
b1 = Button(f1, text="6", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="5", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="4", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="x", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
f1.pack()
f1 = Frame(root, bg="darkgray")
b1 = Button(f1, text="3", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="2", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="1", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="-", padx=21, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
f1.pack()

f1 = Frame(root, bg="darkgray")
b1 = Button(f1, text="0", padx=22, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="c", padx=19, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="=", padx=19, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
b1 = Button(f1, text="+", padx=22, pady=10, font="aerial 15 bold")
b1.pack(side=LEFT, padx=8, pady=12)
b1.bind("<Button-1>", click)
f1.pack()
print(f"{width}x{height}")
Button(text="close", command=root.destroy).pack()
root.mainloop()



